#index:
#    path: /
#    controller: App\Controller\DefaultController::index
invoices:
            path: /invoices
            controller: App\Controller\InvoiceController::invoices


invoice_add:
            path: /invoice/add
            controller: App\Controller\InvoiceAddController::invoice_add
            
invoice_clear_all_forms:
            path: /invoice/clear/all/forms
            controller: App\Controller\InvoiceAddController::invoice_clear_all_forms

position_add:
            path: /position/add/{quantity}/{id_position}
            controller: App\Controller\InvoiceAddController::position_add

position_delete:
            path: /position/delete/{quantity}/{id_position}
            controller: App\Controller\InvoiceAddController::position_delete

position_delete_whole:
            path: /position/delete/whole/{id_position}
            controller: App\Controller\InvoiceAddController::position_delete_whole


ajax_search_invoice_supplier:
            path: /ajax/search/invoice/supplier
            controller: App\Controller\AjaxSearchController::ajax_search_invoice_supplier

ajax_search_invoice_recipient:
            path: /ajax/search/invoice/recipient
            controller: App\Controller\AjaxSearchController::ajax_search_invoice_recipient

ajax_search_invoice_position:
            path: /ajax/search/invoice/position
            controller: App\Controller\AjaxSearchController::ajax_search_invoice_position



invoice_edit:
            path: /invoice/edit/{id_invoice}
            controller: App\Controller\InvoiceEditController::invoice_edit

