#index:
#    path: /
#    controller: App\Controller\DefaultController::index
invoices:
            path: /invoices
            controller: App\Controller\InvoiceController::invoices

invoice_add:
            path: /invoice/add
            controller: App\Controller\InvoiceAddController::invoice_add 

            
invoice_add_clear_all:
            path: /invoice/add/clear/all
            controller: App\Controller\InvoiceAddController::invoice_add_clear_all

invoice_add_position_add:
            path: /position/add/{quantity}/{id_position}
            controller: App\Controller\InvoiceAddController::invoice_add_position_add

invoice_add_position_delete:
            path: /position/delete/{quantity}/{id_position}
            controller: App\Controller\InvoiceAddController::invoice_add_position_delete

invoice_add_position_delete_whole:
            path: /position/deletewhole/{id_position}
            controller: App\Controller\InvoiceAddController::invoice_add_position_delete_whole




invoice_edit:
            path: /invoice/edit/{id_invoice}
            controller: App\Controller\InvoiceEditController::invoice_edit

invoice_delete:
            path: /invoice/delete/{id_invoice}
            controller: App\Controller\InvoiceEditController::invoice_delete          

invoice_edit_clear_all:
            path: /invoice/edit/clear/all/{id_invoice}
            controller: App\Controller\InvoiceEditController::invoice_edit_clear_all

invoice_edit_save_positions:
            path: /invoice/edit/save/positions/{id_invoice}
            controller: App\Controller\InvoiceEditController::invoice_edit_save_positions

invoice_edit_position_add:
            path: /position/add/edit/{quantity}/{id_position}/{id_invoice}
            controller: App\Controller\InvoiceEditController::invoice_edit_position_add

invoice_edit_position_delete:
            path: /position/delete/edit/{quantity}/{id_position}/{id_invoice}
            controller: App\Controller\InvoiceEditController::invoice_edit_position_delete

invoice_edit_position_delete_whole:
            path: /position/deletewhole/edit/{id_position}/{id_invoice}
            controller: App\Controller\InvoiceEditController::invoice_edit_position_delete_whole            




ajax_search_invoice_supplier:
            path: /ajax/search/invoice/supplier
            controller: App\Controller\AjaxSearchController::ajax_search_invoice_supplier

ajax_search_invoice_recipient:
            path: /ajax/search/invoice/recipient
            controller: App\Controller\AjaxSearchController::ajax_search_invoice_recipient

ajax_search_invoice_position:
            path: /ajax/search/invoice/position
            controller: App\Controller\AjaxSearchController::ajax_search_invoice_position





