#index:
#    path: /
#    controller: App\Controller\DefaultController::index
invoices:
            path: /invoices
            controller: App\Controller\InvoiceController::invoices

invoice_edit:
            path: /invoice/edit/{id_invoice}
            controller: App\Controller\InvoiceEditController::invoice_edit

position_add:
            path: /position/add/{id_invoice}/{id_position}
            controller: App\Controller\InvoiceEditController::position_add

position_delete:
            path: /position/delete/{id_invoice}/{id_position}
            controller: App\Controller\InvoiceEditController::position_delete

ajax_search_invoice_supplier:
            path: /ajax/search/invoice/supplier
            controller: App\Controller\AjaxSearchController::ajax_search_invoice_supplier

ajax_search_invoice_recipient:
            path: /ajax/search/invoice/recipient
            controller: App\Controller\AjaxSearchController::ajax_search_invoice_recipient